//! Go `config.BidderInfo` as far as the seller reads it, loaded from the embedded
//! `bidder-info/*.yaml` (the seller's `//go:embed bidder-info/*`, copied from the Prebid module
//! by `scripts/copy-prebid-files.sh`).
//!
//! The seller's `loadBidderInfo` unmarshals the YAML as is: an alias file with no `endpoint` of
//! its own keeps an empty endpoint (27 of the 77 alias files). No alias resolution is done here
//! either.

use serde::Deserialize;

use crate::config;

/// Go `config.AdapterXAPI`.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct Xapi {
    #[serde(default)]
    pub username: String,
    #[serde(default)]
    pub password: String,
    #[serde(default)]
    pub tracker: String,
}

/// The `BidderInfo` fields the seller uses (`prebid_buyer.go`).
#[derive(Debug, Clone, Default, Deserialize)]
pub struct BidderInfo {
    #[serde(default)]
    pub endpoint: String,
    #[serde(default, rename = "extra_info")]
    pub extra_adapter_info: String,
    #[serde(default, rename = "platform_id")]
    pub platform_id: String,
    #[serde(default, rename = "app_secret")]
    pub app_secret: String,
    #[serde(default)]
    pub xapi: Xapi,
    /// `endpointCompression`: `GZIP` makes the seller gzip the request body.
    #[serde(default, rename = "endpointCompression")]
    pub endpoint_compression: String,
    #[serde(default, rename = "gvlVendorID")]
    pub gvl_vendor_id: u16,
}

impl BidderInfo {
    /// Go: `strings.ToLower(bidderInfo.EndpointCompression) == "gzip"`.
    pub fn gzip_requests(&self) -> bool {
        self.endpoint_compression.eq_ignore_ascii_case("gzip")
    }

    /// The `config.Adapter` the seller builds from it (`loadBidderInfo`).
    pub fn adapter_config(&self) -> config::Adapter {
        config::Adapter {
            endpoint: self.endpoint.clone(),
            extra_adapter_info: self.extra_adapter_info.clone(),
            xapi: config::AdapterXapi {
                username: self.xapi.username.clone(),
                password: self.xapi.password.clone(),
                tracker: self.xapi.tracker.clone(),
            },
            platform_id: self.platform_id.clone(),
            app_secret: self.app_secret.clone(),
        }
    }
}

/// Raw YAML of one bidder (Go `f.ReadFile("bidder-info/" + name + ".yaml")`).
pub fn raw(name: &str) -> Option<&'static str> {
    match name {
        "152media" => Some(include_str!("../bidder-info/152media.yaml")),
        "1accord" => Some(include_str!("../bidder-info/1accord.yaml")),
        "33across" => Some(include_str!("../bidder-info/33across.yaml")),
        "360playvid" => Some(include_str!("../bidder-info/360playvid.yaml")),
        "aax" => Some(include_str!("../bidder-info/aax.yaml")),
        "aceex" => Some(include_str!("../bidder-info/aceex.yaml")),
        "acuityads" => Some(include_str!("../bidder-info/acuityads.yaml")),
        "adagio" => Some(include_str!("../bidder-info/adagio.yaml")),
        "addigi" => Some(include_str!("../bidder-info/addigi.yaml")),
        "adelement" => Some(include_str!("../bidder-info/adelement.yaml")),
        "adf" => Some(include_str!("../bidder-info/adf.yaml")),
        "adform" => Some(include_str!("../bidder-info/adform.yaml")),
        "adgeneration" => Some(include_str!("../bidder-info/adgeneration.yaml")),
        "adhese" => Some(include_str!("../bidder-info/adhese.yaml")),
        "adinify" => Some(include_str!("../bidder-info/adinify.yaml")),
        "adipolo" => Some(include_str!("../bidder-info/adipolo.yaml")),
        "adkernel" => Some(include_str!("../bidder-info/adkernel.yaml")),
        "adkernelAdn" => Some(include_str!("../bidder-info/adkernelAdn.yaml")),
        "adman" => Some(include_str!("../bidder-info/adman.yaml")),
        "admatic" => Some(include_str!("../bidder-info/admatic.yaml")),
        "admaticde" => Some(include_str!("../bidder-info/admaticde.yaml")),
        "admixer" => Some(include_str!("../bidder-info/admixer.yaml")),
        "adnuntius" => Some(include_str!("../bidder-info/adnuntius.yaml")),
        "adocean" => Some(include_str!("../bidder-info/adocean.yaml")),
        "adoppler" => Some(include_str!("../bidder-info/adoppler.yaml")),
        "adot" => Some(include_str!("../bidder-info/adot.yaml")),
        "adpone" => Some(include_str!("../bidder-info/adpone.yaml")),
        "adport" => Some(include_str!("../bidder-info/adport.yaml")),
        "adprime" => Some(include_str!("../bidder-info/adprime.yaml")),
        "adquery" => Some(include_str!("../bidder-info/adquery.yaml")),
        "adrino" => Some(include_str!("../bidder-info/adrino.yaml")),
        "ads_interactive" => Some(include_str!("../bidder-info/ads_interactive.yaml")),
        "adsinteractive" => Some(include_str!("../bidder-info/adsinteractive.yaml")),
        "adsyield" => Some(include_str!("../bidder-info/adsyield.yaml")),
        "adt" => Some(include_str!("../bidder-info/adt.yaml")),
        "adtarget" => Some(include_str!("../bidder-info/adtarget.yaml")),
        "adtelligent" => Some(include_str!("../bidder-info/adtelligent.yaml")),
        "adtg_org" => Some(include_str!("../bidder-info/adtg_org.yaml")),
        "adtonos" => Some(include_str!("../bidder-info/adtonos.yaml")),
        "adtrgtme" => Some(include_str!("../bidder-info/adtrgtme.yaml")),
        "aduptech" => Some(include_str!("../bidder-info/aduptech.yaml")),
        "advangelists" => Some(include_str!("../bidder-info/advangelists.yaml")),
        "adverxo" => Some(include_str!("../bidder-info/adverxo.yaml")),
        "adview" => Some(include_str!("../bidder-info/adview.yaml")),
        "adxcg" => Some(include_str!("../bidder-info/adxcg.yaml")),
        "adyoulike" => Some(include_str!("../bidder-info/adyoulike.yaml")),
        "afront" => Some(include_str!("../bidder-info/afront.yaml")),
        "aidem" => Some(include_str!("../bidder-info/aidem.yaml")),
        "aja" => Some(include_str!("../bidder-info/aja.yaml")),
        "akcelo" => Some(include_str!("../bidder-info/akcelo.yaml")),
        "algorix" => Some(include_str!("../bidder-info/algorix.yaml")),
        "alkimi" => Some(include_str!("../bidder-info/alkimi.yaml")),
        "amx" => Some(include_str!("../bidder-info/amx.yaml")),
        "apacdex" => Some(include_str!("../bidder-info/apacdex.yaml")),
        "appStockSSP" => Some(include_str!("../bidder-info/appStockSSP.yaml")),
        "appnexus" => Some(include_str!("../bidder-info/appnexus.yaml")),
        "appstock" => Some(include_str!("../bidder-info/appstock.yaml")),
        "appush" => Some(include_str!("../bidder-info/appush.yaml")),
        "artechnology" => Some(include_str!("../bidder-info/artechnology.yaml")),
        "aso" => Some(include_str!("../bidder-info/aso.yaml")),
        "audienceNetwork" => Some(include_str!("../bidder-info/audienceNetwork.yaml")),
        "automatad" => Some(include_str!("../bidder-info/automatad.yaml")),
        "avocet" => Some(include_str!("../bidder-info/avocet.yaml")),
        "axis" => Some(include_str!("../bidder-info/axis.yaml")),
        "axonix" => Some(include_str!("../bidder-info/axonix.yaml")),
        "bcmint" => Some(include_str!("../bidder-info/bcmint.yaml")),
        "beachfront" => Some(include_str!("../bidder-info/beachfront.yaml")),
        "beintoo" => Some(include_str!("../bidder-info/beintoo.yaml")),
        "bematterfull" => Some(include_str!("../bidder-info/bematterfull.yaml")),
        "between" => Some(include_str!("../bidder-info/between.yaml")),
        "beyondmedia" => Some(include_str!("../bidder-info/beyondmedia.yaml")),
        "bidgency" => Some(include_str!("../bidder-info/bidgency.yaml")),
        "bidmachine" => Some(include_str!("../bidder-info/bidmachine.yaml")),
        "bidmatic" => Some(include_str!("../bidder-info/bidmatic.yaml")),
        "bidmyadz" => Some(include_str!("../bidder-info/bidmyadz.yaml")),
        "bidscube" => Some(include_str!("../bidder-info/bidscube.yaml")),
        "bidsmind" => Some(include_str!("../bidder-info/bidsmind.yaml")),
        "bidstack" => Some(include_str!("../bidder-info/bidstack.yaml")),
        "bidtheatre" => Some(include_str!("../bidder-info/bidtheatre.yaml")),
        "bigoad" => Some(include_str!("../bidder-info/bigoad.yaml")),
        "blasto" => Some(include_str!("../bidder-info/blasto.yaml")),
        "bliink" => Some(include_str!("../bidder-info/bliink.yaml")),
        "blis" => Some(include_str!("../bidder-info/blis.yaml")),
        "blue" => Some(include_str!("../bidder-info/blue.yaml")),
        "bluesea" => Some(include_str!("../bidder-info/bluesea.yaml")),
        "bmtm" => Some(include_str!("../bidder-info/bmtm.yaml")),
        "boldwin" => Some(include_str!("../bidder-info/boldwin.yaml")),
        "boldwin_rapid" => Some(include_str!("../bidder-info/boldwin_rapid.yaml")),
        "brave" => Some(include_str!("../bidder-info/brave.yaml")),
        "bwx" => Some(include_str!("../bidder-info/bwx.yaml")),
        "cadent_aperture_mx" => Some(include_str!("../bidder-info/cadent_aperture_mx.yaml")),
        "ccx" => Some(include_str!("../bidder-info/ccx.yaml")),
        "clydo" => Some(include_str!("../bidder-info/clydo.yaml")),
        "cointraffic" => Some(include_str!("../bidder-info/cointraffic.yaml")),
        "coinzilla" => Some(include_str!("../bidder-info/coinzilla.yaml")),
        "colossus" => Some(include_str!("../bidder-info/colossus.yaml")),
        "compass" => Some(include_str!("../bidder-info/compass.yaml")),
        "concert" => Some(include_str!("../bidder-info/concert.yaml")),
        "connatix" => Some(include_str!("../bidder-info/connatix.yaml")),
        "connectad" => Some(include_str!("../bidder-info/connectad.yaml")),
        "connektai" => Some(include_str!("../bidder-info/connektai.yaml")),
        "consumable" => Some(include_str!("../bidder-info/consumable.yaml")),
        "contxtful" => Some(include_str!("../bidder-info/contxtful.yaml")),
        "conversant" => Some(include_str!("../bidder-info/conversant.yaml")),
        "copper6" => Some(include_str!("../bidder-info/copper6.yaml")),
        "copper6ssp" => Some(include_str!("../bidder-info/copper6ssp.yaml")),
        "cpmstar" => Some(include_str!("../bidder-info/cpmstar.yaml")),
        "criteo" => Some(include_str!("../bidder-info/criteo.yaml")),
        "cwire" => Some(include_str!("../bidder-info/cwire.yaml")),
        "datablocks" => Some(include_str!("../bidder-info/datablocks.yaml")),
        "decenterads" => Some(include_str!("../bidder-info/decenterads.yaml")),
        "deepintent" => Some(include_str!("../bidder-info/deepintent.yaml")),
        "definemedia" => Some(include_str!("../bidder-info/definemedia.yaml")),
        "dianomi" => Some(include_str!("../bidder-info/dianomi.yaml")),
        "displayio" => Some(include_str!("../bidder-info/displayio.yaml")),
        "dmx" => Some(include_str!("../bidder-info/dmx.yaml")),
        "driftpixel" => Some(include_str!("../bidder-info/driftpixel.yaml")),
        "dxkulture" => Some(include_str!("../bidder-info/dxkulture.yaml")),
        "e_volution" => Some(include_str!("../bidder-info/e_volution.yaml")),
        "easybid" => Some(include_str!("../bidder-info/easybid.yaml")),
        "edge226" => Some(include_str!("../bidder-info/edge226.yaml")),
        "embimedia" => Some(include_str!("../bidder-info/embimedia.yaml")),
        "emtv" => Some(include_str!("../bidder-info/emtv.yaml")),
        "emx_digital" => Some(include_str!("../bidder-info/emx_digital.yaml")),
        "eplanning" => Some(include_str!("../bidder-info/eplanning.yaml")),
        "epom" => Some(include_str!("../bidder-info/epom.yaml")),
        "epsilon" => Some(include_str!("../bidder-info/epsilon.yaml")),
        "equativ" => Some(include_str!("../bidder-info/equativ.yaml")),
        "escalax" => Some(include_str!("../bidder-info/escalax.yaml")),
        "evtech" => Some(include_str!("../bidder-info/evtech.yaml")),
        "exco" => Some(include_str!("../bidder-info/exco.yaml")),
        "feedad" => Some(include_str!("../bidder-info/feedad.yaml")),
        "felixads" => Some(include_str!("../bidder-info/felixads.yaml")),
        "filmzie" => Some(include_str!("../bidder-info/filmzie.yaml")),
        "finative" => Some(include_str!("../bidder-info/finative.yaml")),
        "flatads" => Some(include_str!("../bidder-info/flatads.yaml")),
        "flipp" => Some(include_str!("../bidder-info/flipp.yaml")),
        "freewheel-ssp" => Some(include_str!("../bidder-info/freewheel-ssp.yaml")),
        "freewheelssp" => Some(include_str!("../bidder-info/freewheelssp.yaml")),
        "frvradn" => Some(include_str!("../bidder-info/frvradn.yaml")),
        "fwssp" => Some(include_str!("../bidder-info/fwssp.yaml")),
        "gamma" => Some(include_str!("../bidder-info/gamma.yaml")),
        "gamoshi" => Some(include_str!("../bidder-info/gamoshi.yaml")),
        "globalsun" => Some(include_str!("../bidder-info/globalsun.yaml")),
        "goldbach" => Some(include_str!("../bidder-info/goldbach.yaml")),
        "gothamads" => Some(include_str!("../bidder-info/gothamads.yaml")),
        "gravite" => Some(include_str!("../bidder-info/gravite.yaml")),
        "greedygame" => Some(include_str!("../bidder-info/greedygame.yaml")),
        "grid" => Some(include_str!("../bidder-info/grid.yaml")),
        "gumgum" => Some(include_str!("../bidder-info/gumgum.yaml")),
        "huaweiads" => Some(include_str!("../bidder-info/huaweiads.yaml")),
        "iionads" => Some(include_str!("../bidder-info/iionads.yaml")),
        "imds" => Some(include_str!("../bidder-info/imds.yaml")),
        "impactify" => Some(include_str!("../bidder-info/impactify.yaml")),
        "improvedigital" => Some(include_str!("../bidder-info/improvedigital.yaml")),
        "indicue" => Some(include_str!("../bidder-info/indicue.yaml")),
        "infytv" => Some(include_str!("../bidder-info/infytv.yaml")),
        "inmobi" => Some(include_str!("../bidder-info/inmobi.yaml")),
        "insticator" => Some(include_str!("../bidder-info/insticator.yaml")),
        "intenze" => Some(include_str!("../bidder-info/intenze.yaml")),
        "interactiveoffers" => Some(include_str!("../bidder-info/interactiveoffers.yaml")),
        "intertech" => Some(include_str!("../bidder-info/intertech.yaml")),
        "invibes" => Some(include_str!("../bidder-info/invibes.yaml")),
        "iqx" => Some(include_str!("../bidder-info/iqx.yaml")),
        "iqzone" => Some(include_str!("../bidder-info/iqzone.yaml")),
        "ix" => Some(include_str!("../bidder-info/ix.yaml")),
        "jambojar" => Some(include_str!("../bidder-info/jambojar.yaml")),
        "janet" => Some(include_str!("../bidder-info/janet.yaml")),
        "jdpmedia" => Some(include_str!("../bidder-info/jdpmedia.yaml")),
        "jixie" => Some(include_str!("../bidder-info/jixie.yaml")),
        "kargo" => Some(include_str!("../bidder-info/kargo.yaml")),
        "kayzen" => Some(include_str!("../bidder-info/kayzen.yaml")),
        "kidoz" => Some(include_str!("../bidder-info/kidoz.yaml")),
        "kiviads" => Some(include_str!("../bidder-info/kiviads.yaml")),
        "kobler" => Some(include_str!("../bidder-info/kobler.yaml")),
        "krushmedia" => Some(include_str!("../bidder-info/krushmedia.yaml")),
        "kuantyx" => Some(include_str!("../bidder-info/kuantyx.yaml")),
        "kueezrtb" => Some(include_str!("../bidder-info/kueezrtb.yaml")),
        "lemmadigital" => Some(include_str!("../bidder-info/lemmadigital.yaml")),
        "limelightDigital" => Some(include_str!("../bidder-info/limelightDigital.yaml")),
        "lm_kiviads" => Some(include_str!("../bidder-info/lm_kiviads.yaml")),
        "lockerdome" => Some(include_str!("../bidder-info/lockerdome.yaml")),
        "logan" => Some(include_str!("../bidder-info/logan.yaml")),
        "logicad" => Some(include_str!("../bidder-info/logicad.yaml")),
        "loopme" => Some(include_str!("../bidder-info/loopme.yaml")),
        "loyal" => Some(include_str!("../bidder-info/loyal.yaml")),
        "lunamedia" => Some(include_str!("../bidder-info/lunamedia.yaml")),
        "mabidder" => Some(include_str!("../bidder-info/mabidder.yaml")),
        "madsense" => Some(include_str!("../bidder-info/madsense.yaml")),
        "madvertise" => Some(include_str!("../bidder-info/madvertise.yaml")),
        "magnite" => Some(include_str!("../bidder-info/magnite.yaml")),
        "markapp" => Some(include_str!("../bidder-info/markapp.yaml")),
        "marsmedia" => Some(include_str!("../bidder-info/marsmedia.yaml")),
        "mediafuse" => Some(include_str!("../bidder-info/mediafuse.yaml")),
        "mediago" => Some(include_str!("../bidder-info/mediago.yaml")),
        "medianet" => Some(include_str!("../bidder-info/medianet.yaml")),
        "mediasquare" => Some(include_str!("../bidder-info/mediasquare.yaml")),
        "mediayo" => Some(include_str!("../bidder-info/mediayo.yaml")),
        "melozen" => Some(include_str!("../bidder-info/melozen.yaml")),
        "metax" => Some(include_str!("../bidder-info/metax.yaml")),
        "mgid" => Some(include_str!("../bidder-info/mgid.yaml")),
        "mgidX" => Some(include_str!("../bidder-info/mgidX.yaml")),
        "minutemedia" => Some(include_str!("../bidder-info/minutemedia.yaml")),
        "missena" => Some(include_str!("../bidder-info/missena.yaml")),
        "mobfoxpb" => Some(include_str!("../bidder-info/mobfoxpb.yaml")),
        "mobilefuse" => Some(include_str!("../bidder-info/mobilefuse.yaml")),
        "mobkoi" => Some(include_str!("../bidder-info/mobkoi.yaml")),
        "mobupps" => Some(include_str!("../bidder-info/mobupps.yaml")),
        "monetixads" => Some(include_str!("../bidder-info/monetixads.yaml")),
        "motorik" => Some(include_str!("../bidder-info/motorik.yaml")),
        "msft" => Some(include_str!("../bidder-info/msft.yaml")),
        "nativery" => Some(include_str!("../bidder-info/nativery.yaml")),
        "nativo" => Some(include_str!("../bidder-info/nativo.yaml")),
        "netaddiction" => Some(include_str!("../bidder-info/netaddiction.yaml")),
        "nextmillennium" => Some(include_str!("../bidder-info/nextmillennium.yaml")),
        "nexx360" => Some(include_str!("../bidder-info/nexx360.yaml")),
        "nobid" => Some(include_str!("../bidder-info/nobid.yaml")),
        "ogury" => Some(include_str!("../bidder-info/ogury.yaml")),
        "omnidex" => Some(include_str!("../bidder-info/omnidex.yaml")),
        "oms" => Some(include_str!("../bidder-info/oms.yaml")),
        "onetag" => Some(include_str!("../bidder-info/onetag.yaml")),
        "openweb" => Some(include_str!("../bidder-info/openweb.yaml")),
        "openx" => Some(include_str!("../bidder-info/openx.yaml")),
        "operaads" => Some(include_str!("../bidder-info/operaads.yaml")),
        "optidigital" => Some(include_str!("../bidder-info/optidigital.yaml")),
        "oraki" => Some(include_str!("../bidder-info/oraki.yaml")),
        "orangeclickmedia" => Some(include_str!("../bidder-info/orangeclickmedia.yaml")),
        "orbidder" => Some(include_str!("../bidder-info/orbidder.yaml")),
        "outbrain" => Some(include_str!("../bidder-info/outbrain.yaml")),
        "ownadx" => Some(include_str!("../bidder-info/ownadx.yaml")),
        "pangle" => Some(include_str!("../bidder-info/pangle.yaml")),
        "performist" => Some(include_str!("../bidder-info/performist.yaml")),
        "pgam" => Some(include_str!("../bidder-info/pgam.yaml")),
        "pgamssp" => Some(include_str!("../bidder-info/pgamssp.yaml")),
        "pinkLion" => Some(include_str!("../bidder-info/pinkLion.yaml")),
        "pixad" => Some(include_str!("../bidder-info/pixad.yaml")),
        "playdigo" => Some(include_str!("../bidder-info/playdigo.yaml")),
        "prismassp" => Some(include_str!("../bidder-info/prismassp.yaml")),
        "progx" => Some(include_str!("../bidder-info/progx.yaml")),
        "pubmatic" => Some(include_str!("../bidder-info/pubmatic.yaml")),
        "pubnative" => Some(include_str!("../bidder-info/pubnative.yaml")),
        "pubrise" => Some(include_str!("../bidder-info/pubrise.yaml")),
        "pulsepoint" => Some(include_str!("../bidder-info/pulsepoint.yaml")),
        "pwbid" => Some(include_str!("../bidder-info/pwbid.yaml")),
        "qt" => Some(include_str!("../bidder-info/qt.yaml")),
        "quantumdex" => Some(include_str!("../bidder-info/quantumdex.yaml")),
        "readpeak" => Some(include_str!("../bidder-info/readpeak.yaml")),
        "rediads" => Some(include_str!("../bidder-info/rediads.yaml")),
        "relevantdigital" => Some(include_str!("../bidder-info/relevantdigital.yaml")),
        "resetdigital" => Some(include_str!("../bidder-info/resetdigital.yaml")),
        "revcontent" => Some(include_str!("../bidder-info/revcontent.yaml")),
        "richaudience" => Some(include_str!("../bidder-info/richaudience.yaml")),
        "rise" => Some(include_str!("../bidder-info/rise.yaml")),
        "robustApps" => Some(include_str!("../bidder-info/robustApps.yaml")),
        "rocketlab" => Some(include_str!("../bidder-info/rocketlab.yaml")),
        "roulax" => Some(include_str!("../bidder-info/roulax.yaml")),
        "rtbhouse" => Some(include_str!("../bidder-info/rtbhouse.yaml")),
        "rubicon" => Some(include_str!("../bidder-info/rubicon.yaml")),
        "rxnetwork" => Some(include_str!("../bidder-info/rxnetwork.yaml")),
        "sa_lunamedia" => Some(include_str!("../bidder-info/sa_lunamedia.yaml")),
        "screencore" => Some(include_str!("../bidder-info/screencore.yaml")),
        "seedingAlliance" => Some(include_str!("../bidder-info/seedingAlliance.yaml")),
        "seedtag" => Some(include_str!("../bidder-info/seedtag.yaml")),
        "sharethrough" => Some(include_str!("../bidder-info/sharethrough.yaml")),
        "showheroes" => Some(include_str!("../bidder-info/showheroes.yaml")),
        "showheroes-bs" => Some(include_str!("../bidder-info/showheroes-bs.yaml")),
        "showheroesBs" => Some(include_str!("../bidder-info/showheroesBs.yaml")),
        "silvermob" => Some(include_str!("../bidder-info/silvermob.yaml")),
        "silverpush" => Some(include_str!("../bidder-info/silverpush.yaml")),
        "smaato" => Some(include_str!("../bidder-info/smaato.yaml")),
        "smartadserver" => Some(include_str!("../bidder-info/smartadserver.yaml")),
        "smarthub" => Some(include_str!("../bidder-info/smarthub.yaml")),
        "smartrtb" => Some(include_str!("../bidder-info/smartrtb.yaml")),
        "smartx" => Some(include_str!("../bidder-info/smartx.yaml")),
        "smartyads" => Some(include_str!("../bidder-info/smartyads.yaml")),
        "smilewanted" => Some(include_str!("../bidder-info/smilewanted.yaml")),
        "smoot" => Some(include_str!("../bidder-info/smoot.yaml")),
        "smrtconnect" => Some(include_str!("../bidder-info/smrtconnect.yaml")),
        "sonobi" => Some(include_str!("../bidder-info/sonobi.yaml")),
        "sovrn" => Some(include_str!("../bidder-info/sovrn.yaml")),
        "sovrnXsp" => Some(include_str!("../bidder-info/sovrnXsp.yaml")),
        "sparteo" => Some(include_str!("../bidder-info/sparteo.yaml")),
        "sspBC" => Some(include_str!("../bidder-info/sspBC.yaml")),
        "startio" => Some(include_str!("../bidder-info/startio.yaml")),
        "streamkey" => Some(include_str!("../bidder-info/streamkey.yaml")),
        "streamlyn" => Some(include_str!("../bidder-info/streamlyn.yaml")),
        "streamvision" => Some(include_str!("../bidder-info/streamvision.yaml")),
        "stroeerCore" => Some(include_str!("../bidder-info/stroeerCore.yaml")),
        "suntContent" => Some(include_str!("../bidder-info/suntContent.yaml")),
        "synacormedia" => Some(include_str!("../bidder-info/synacormedia.yaml")),
        "taboola" => Some(include_str!("../bidder-info/taboola.yaml")),
        "tagoras" => Some(include_str!("../bidder-info/tagoras.yaml")),
        "tappx" => Some(include_str!("../bidder-info/tappx.yaml")),
        "teads" => Some(include_str!("../bidder-info/teads.yaml")),
        "telaria" => Some(include_str!("../bidder-info/telaria.yaml")),
        "teqblaze" => Some(include_str!("../bidder-info/teqblaze.yaml")),
        "tgm" => Some(include_str!("../bidder-info/tgm.yaml")),
        "theadx" => Some(include_str!("../bidder-info/theadx.yaml")),
        "thetradedesk" => Some(include_str!("../bidder-info/thetradedesk.yaml")),
        "tpmn" => Some(include_str!("../bidder-info/tpmn.yaml")),
        "tradplus" => Some(include_str!("../bidder-info/tradplus.yaml")),
        "trafficgate" => Some(include_str!("../bidder-info/trafficgate.yaml")),
        "tredio" => Some(include_str!("../bidder-info/tredio.yaml")),
        "triplelift" => Some(include_str!("../bidder-info/triplelift.yaml")),
        "triplelift_native" => Some(include_str!("../bidder-info/triplelift_native.yaml")),
        "trustedstack" => Some(include_str!("../bidder-info/trustedstack.yaml")),
        "trustx" => Some(include_str!("../bidder-info/trustx.yaml")),
        "ttd" => Some(include_str!("../bidder-info/ttd.yaml")),
        "ucfunnel" => Some(include_str!("../bidder-info/ucfunnel.yaml")),
        "undertone" => Some(include_str!("../bidder-info/undertone.yaml")),
        "unicorn" => Some(include_str!("../bidder-info/unicorn.yaml")),
        "unruly" => Some(include_str!("../bidder-info/unruly.yaml")),
        "valueimpression" => Some(include_str!("../bidder-info/valueimpression.yaml")),
        "velonium" => Some(include_str!("../bidder-info/velonium.yaml")),
        "vidazoo" => Some(include_str!("../bidder-info/vidazoo.yaml")),
        "videobyte" => Some(include_str!("../bidder-info/videobyte.yaml")),
        "videoheroes" => Some(include_str!("../bidder-info/videoheroes.yaml")),
        "vidoomy" => Some(include_str!("../bidder-info/vidoomy.yaml")),
        "viewdeos" => Some(include_str!("../bidder-info/viewdeos.yaml")),
        "vimayx" => Some(include_str!("../bidder-info/vimayx.yaml")),
        "visiblemeasures" => Some(include_str!("../bidder-info/visiblemeasures.yaml")),
        "visx" => Some(include_str!("../bidder-info/visx.yaml")),
        "vox" => Some(include_str!("../bidder-info/vox.yaml")),
        "vrtcal" => Some(include_str!("../bidder-info/vrtcal.yaml")),
        "vungle" => Some(include_str!("../bidder-info/vungle.yaml")),
        "xapads" => Some(include_str!("../bidder-info/xapads.yaml")),
        "xeworks" => Some(include_str!("../bidder-info/xeworks.yaml")),
        "xtrmqb" => Some(include_str!("../bidder-info/xtrmqb.yaml")),
        "yahooAds" => Some(include_str!("../bidder-info/yahooAds.yaml")),
        "yahooAdvertising" => Some(include_str!("../bidder-info/yahooAdvertising.yaml")),
        "yahoossp" => Some(include_str!("../bidder-info/yahoossp.yaml")),
        "yandex" => Some(include_str!("../bidder-info/yandex.yaml")),
        "yeahmobi" => Some(include_str!("../bidder-info/yeahmobi.yaml")),
        "yieldlab" => Some(include_str!("../bidder-info/yieldlab.yaml")),
        "yieldmo" => Some(include_str!("../bidder-info/yieldmo.yaml")),
        "yieldone" => Some(include_str!("../bidder-info/yieldone.yaml")),
        "yobee" => Some(include_str!("../bidder-info/yobee.yaml")),
        "zentotem" => Some(include_str!("../bidder-info/zentotem.yaml")),
        "zeroclickfraud" => Some(include_str!("../bidder-info/zeroclickfraud.yaml")),
        "zeta_global_ssp" => Some(include_str!("../bidder-info/zeta_global_ssp.yaml")),
        "zmaticoo" => Some(include_str!("../bidder-info/zmaticoo.yaml")),
        _ => None,
    }
}

/// Go `loadBidderInfo` minus the builder: parse the embedded YAML for `name`.
pub fn load(name: &str) -> Result<BidderInfo, String> {
    let data = raw(name).ok_or_else(|| format!("open bidder-info/{name}.yaml: file does not exist"))?;
    serde_yaml::from_str(data).map_err(|e| format!("error parsing config for bidder {name}: {e}"))
}
