//! Bidder name to adapter (Go `PrebidAdapterBuilders` in the seller's `prebid_builders.go`).
//!
//! Generated from that map: 240 bidder names over 238 adapters (`emx_digital` shares
//! `cadent_aperture_mx`, `mediafuse` shares `appnexus`).

use crate::adapters;
use crate::bidder::Bidder;
use crate::config;

/// Every bidder name the seller can build, sorted.
pub const BIDDER_NAMES: &[&str] = &[
    "33across",
    "aax",
    "aceex",
    "acuityads",
    "adelement",
    "adf",
    "adgeneration",
    "adhese",
    "adkernel",
    "adkernelAdn",
    "adman",
    "admatic",
    "admixer",
    "adnuntius",
    "adocean",
    "adoppler",
    "adot",
    "adpone",
    "adprime",
    "adquery",
    "adrino",
    "ads_interactive",
    "adsinteractive",
    "adtarget",
    "adtelligent",
    "adtonos",
    "adtrgtme",
    "aduptech",
    "advangelists",
    "adverxo",
    "adview",
    "adxcg",
    "adyoulike",
    "aidem",
    "aja",
    "algorix",
    "alkimi",
    "amx",
    "apacdex",
    "appnexus",
    "appush",
    "aso",
    "audienceNetwork",
    "automatad",
    "avocet",
    "axis",
    "axonix",
    "beachfront",
    "beintoo",
    "bematterfull",
    "between",
    "beyondmedia",
    "bidmachine",
    "bidmatic",
    "bidmyadz",
    "bidscube",
    "bidstack",
    "bidtheatre",
    "bigoad",
    "blasto",
    "bliink",
    "blue",
    "bluesea",
    "bmtm",
    "boldwin",
    "brave",
    "bwx",
    "cadent_aperture_mx",
    "ccx",
    "cointraffic",
    "coinzilla",
    "colossus",
    "compass",
    "concert",
    "connatix",
    "connectad",
    "consumable",
    "conversant",
    "copper6ssp",
    "cpmstar",
    "criteo",
    "cwire",
    "datablocks",
    "decenterads",
    "deepintent",
    "definemedia",
    "dianomi",
    "displayio",
    "dmx",
    "driftpixel",
    "dxkulture",
    "e_volution",
    "edge226",
    "emtv",
    "emx_digital",
    "eplanning",
    "epom",
    "escalax",
    "feedad",
    "flipp",
    "freewheelssp",
    "frvradn",
    "gamma",
    "gamoshi",
    "globalsun",
    "gothamads",
    "grid",
    "gumgum",
    "huaweiads",
    "imds",
    "impactify",
    "improvedigital",
    "infytv",
    "inmobi",
    "insticator",
    "interactiveoffers",
    "intertech",
    "invibes",
    "iqx",
    "iqzone",
    "ix",
    "jixie",
    "kargo",
    "kayzen",
    "kidoz",
    "kiviads",
    "kobler",
    "krushmedia",
    "kueezrtb",
    "lemmadigital",
    "limelightDigital",
    "lm_kiviads",
    "lockerdome",
    "logan",
    "logicad",
    "loopme",
    "loyal",
    "lunamedia",
    "mabidder",
    "madvertise",
    "marsmedia",
    "mediafuse",
    "mediago",
    "medianet",
    "melozen",
    "metax",
    "mgid",
    "mgidX",
    "minutemedia",
    "missena",
    "mobfoxpb",
    "mobilefuse",
    "motorik",
    "nativo",
    "nextmillennium",
    "nobid",
    "ogury",
    "oms",
    "onetag",
    "openweb",
    "openx",
    "operaads",
    "oraki",
    "orbidder",
    "outbrain",
    "ownadx",
    "pangle",
    "pgamssp",
    "playdigo",
    "pubmatic",
    "pubnative",
    "pubrise",
    "pulsepoint",
    "pwbid",
    "qt",
    "readpeak",
    "relevantdigital",
    "resetdigital",
    "revcontent",
    "richaudience",
    "rise",
    "roulax",
    "rtbhouse",
    "rubicon",
    "sa_lunamedia",
    "screencore",
    "seedingAlliance",
    "seedtag",
    "sharethrough",
    "silvermob",
    "silverpush",
    "smaato",
    "smartadserver",
    "smarthub",
    "smartrtb",
    "smartx",
    "smartyads",
    "smilewanted",
    "smoot",
    "smrtconnect",
    "sonobi",
    "sovrn",
    "sovrnXsp",
    "sspBC",
    "stroeerCore",
    "taboola",
    "tappx",
    "teads",
    "telaria",
    "theadx",
    "thetradedesk",
    "tpmn",
    "tradplus",
    "trafficgate",
    "triplelift",
    "triplelift_native",
    "trustedstack",
    "ucfunnel",
    "undertone",
    "unicorn",
    "unruly",
    "vidazoo",
    "videobyte",
    "videoheroes",
    "vidoomy",
    "visiblemeasures",
    "visx",
    "vox",
    "vrtcal",
    "vungle",
    "xeworks",
    "yahooAds",
    "yandex",
    "yeahmobi",
    "yieldlab",
    "yieldmo",
    "yieldone",
    "zeroclickfraud",
    "zeta_global_ssp",
    "zmaticoo",
];

/// Go `adapters.Builder`: `builders[bidderName](bidderName, adapterConfig, serverConfig)`.
pub fn build(name: &str, cfg: &config::Adapter, server: &config::Server) -> Result<Box<dyn Bidder>, String> {
    let _ = (&cfg, &server);
    Ok(match name {
        "33across" => Box::new(adapters::across33::Adapter::new(cfg.endpoint.clone())),
        "aax" => Box::new(adapters::aax::Adapter::new(cfg.endpoint.clone(), cfg.extra_adapter_info.clone())),
        "aceex" => Box::new(adapters::aceex::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "acuityads" => Box::new(adapters::acuityads::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adelement" => Box::new(adapters::adelement::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adf" => Box::new(adapters::adf::Adapter::new(cfg.endpoint.clone())),
        "adgeneration" => Box::new(adapters::adgeneration::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adhese" => Box::new(adapters::adhese::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "adkernel" => Box::new(adapters::adkernel::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adkernelAdn" => Box::new(adapters::adkernel_adn::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "adman" => Box::new(adapters::adman::Adapter::new(cfg.endpoint.clone())),
        "admatic" => Box::new(adapters::admatic::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "admixer" => Box::new(adapters::admixer::Adapter::new(cfg.endpoint.clone())),
        "adnuntius" => Box::new(adapters::adnuntius::Adapter::new(cfg.endpoint.clone(), cfg.extra_adapter_info.clone())),
        "adocean" => Box::new(adapters::adocean::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adoppler" => Box::new(adapters::adoppler::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adot" => Box::new(adapters::adot::Adapter::new(cfg.endpoint.clone())),
        "adpone" => Box::new(adapters::adpone::Adapter::new(cfg.endpoint.clone())),
        "adprime" => Box::new(adapters::adprime::Adapter::new(cfg.endpoint.clone())),
        "adquery" => Box::new(adapters::adquery::Adapter::new(cfg.endpoint.clone())),
        "adrino" => Box::new(adapters::adrino::Adapter::new(cfg.endpoint.clone())),
        "ads_interactive" => Box::new(adapters::ads_interactive::Adapter::new(cfg.endpoint.clone())),
        "adsinteractive" => Box::new(adapters::adsinteractive::Adapter::new(cfg.endpoint.clone())),
        "adtarget" => Box::new(adapters::adtarget::Adapter::new(cfg.endpoint.clone())),
        "adtelligent" => Box::new(adapters::adtelligent::Adapter::new(cfg.endpoint.clone())),
        "adtonos" => Box::new(adapters::adtonos::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adtrgtme" => Box::new(adapters::adtrgtme::Adapter::new(cfg.endpoint.clone())),
        "aduptech" => Box::new(adapters::aduptech::Adapter::new(cfg.endpoint.clone(), &cfg.extra_adapter_info).map_err(|e| e.to_string())?),
        "advangelists" => Box::new(adapters::advangelists::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adverxo" => Box::new(adapters::adverxo::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "adview" => Box::new(adapters::adview::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "adxcg" => Box::new(adapters::adxcg::Adapter::new(cfg.endpoint.clone())),
        "adyoulike" => Box::new(adapters::adyoulike::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "aidem" => Box::new(adapters::aidem::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "aja" => Box::new(adapters::aja::Adapter::new(cfg.endpoint.clone())),
        "algorix" => Box::new(adapters::algorix::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "alkimi" => Box::new(adapters::alkimi::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "amx" => Box::new(adapters::amx::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "apacdex" => Box::new(adapters::apacdex::Adapter::new(cfg.endpoint.clone())),
        "appnexus" => Box::new(adapters::appnexus::Adapter::new(cfg).map_err(|e| e.to_string())?),
        "appush" => Box::new(adapters::appush::Adapter::new(cfg.endpoint.clone())),
        "aso" => Box::new(adapters::aso::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "audienceNetwork" => Box::new(adapters::audience_network::Adapter::new(cfg).map_err(|e| e.to_string())?),
        "automatad" => Box::new(adapters::automatad::Adapter::new(cfg.endpoint.clone())),
        "avocet" => Box::new(adapters::avocet::Adapter::new(cfg.endpoint.clone())),
        "axis" => Box::new(adapters::axis::Adapter::new(cfg.endpoint.clone())),
        "axonix" => Box::new(adapters::axonix::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "beachfront" => Box::new(adapters::beachfront::Adapter::new(cfg.endpoint.clone(), &cfg.extra_adapter_info).map_err(|e| e.to_string())?),
        "beintoo" => Box::new(adapters::beintoo::Adapter::new(cfg.endpoint.clone())),
        "bematterfull" => Box::new(adapters::bematterfull::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "between" => Box::new(adapters::between::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "beyondmedia" => Box::new(adapters::beyondmedia::Adapter::new(cfg.endpoint.clone())),
        "bidmachine" => Box::new(adapters::bidmachine::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "bidmatic" => Box::new(adapters::bidmatic::Adapter::new(cfg.endpoint.clone())),
        "bidmyadz" => Box::new(adapters::bidmyadz::Adapter::new(cfg.endpoint.clone())),
        "bidscube" => Box::new(adapters::bidscube::Adapter::new(cfg.endpoint.clone())),
        "bidstack" => Box::new(adapters::bidstack::Adapter::new(cfg.endpoint.clone())),
        "bidtheatre" => Box::new(adapters::bidtheatre::Adapter::new(cfg.endpoint.clone())),
        "bigoad" => Box::new(adapters::bigoad::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "blasto" => Box::new(adapters::blasto::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "bliink" => Box::new(adapters::bliink::Adapter::new(cfg.endpoint.clone())),
        "blue" => Box::new(adapters::blue::Adapter::new(cfg.endpoint.clone())),
        "bluesea" => Box::new(adapters::bluesea::Adapter::new(cfg.endpoint.clone())),
        "bmtm" => Box::new(adapters::bmtm::Adapter::new(cfg.endpoint.clone())),
        "boldwin" => Box::new(adapters::boldwin::Adapter::new(cfg.endpoint.clone())),
        "brave" => Box::new(adapters::brave::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "bwx" => Box::new(adapters::bwx::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "cadent_aperture_mx" => Box::new(adapters::cadent_aperture_mx::Adapter::new(cfg.endpoint.clone())),
        "ccx" => Box::new(adapters::ccx::Adapter::new(cfg.endpoint.clone())),
        "cointraffic" => Box::new(adapters::cointraffic::Adapter::new(cfg.endpoint.clone())),
        "coinzilla" => Box::new(adapters::coinzilla::Adapter::new(cfg.endpoint.clone())),
        "colossus" => Box::new(adapters::colossus::Adapter::new(cfg.endpoint.clone())),
        "compass" => Box::new(adapters::compass::Adapter::new(cfg.endpoint.clone())),
        "concert" => Box::new(adapters::concert::Adapter::new(cfg.endpoint.clone())),
        "connatix" => Box::new(adapters::connatix::Adapter::new(cfg.endpoint.clone())),
        "connectad" => Box::new(adapters::connectad::Adapter::new(cfg.endpoint.clone())),
        "consumable" => Box::new(adapters::consumable::Adapter::new(cfg.endpoint.clone())),
        "conversant" => Box::new(adapters::conversant::Adapter::new(cfg.endpoint.clone())),
        "copper6ssp" => Box::new(adapters::copper6ssp::Adapter::new(cfg.endpoint.clone())),
        "cpmstar" => Box::new(adapters::cpmstar::Adapter::new(cfg.endpoint.clone())),
        "criteo" => Box::new(adapters::criteo::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "cwire" => Box::new(adapters::cwire::Adapter::new(cfg.endpoint.clone())),
        "datablocks" => Box::new(adapters::datablocks::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "decenterads" => Box::new(adapters::decenterads::Adapter::new(cfg.endpoint.clone())),
        "deepintent" => Box::new(adapters::deepintent::Adapter::new(cfg.endpoint.clone())),
        "definemedia" => Box::new(adapters::definemedia::Adapter::new(cfg.endpoint.clone())),
        "dianomi" => Box::new(adapters::dianomi::Adapter::new(cfg.endpoint.clone())),
        "displayio" => Box::new(adapters::displayio::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "dmx" => Box::new(adapters::dmx::Adapter::new(cfg.endpoint.clone())),
        "driftpixel" => Box::new(adapters::driftpixel::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "dxkulture" => Box::new(adapters::dxkulture::Adapter::new(cfg.endpoint.clone())),
        "e_volution" => Box::new(adapters::e_volution::Adapter::new(cfg.endpoint.clone())),
        "edge226" => Box::new(adapters::edge226::Adapter::new(cfg.endpoint.clone())),
        "emtv" => Box::new(adapters::emtv::Adapter::new(cfg.endpoint.clone())),
        "emx_digital" => Box::new(adapters::cadent_aperture_mx::Adapter::new(cfg.endpoint.clone())),
        "eplanning" => Box::new(adapters::eplanning::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "epom" => Box::new(adapters::epom::Adapter::new(cfg.endpoint.clone())),
        "escalax" => Box::new(adapters::escalax::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "feedad" => Box::new(adapters::feedad::Adapter::new(cfg.endpoint.clone())),
        "flipp" => Box::new(adapters::flipp::Adapter::new(cfg.endpoint.clone())),
        "freewheelssp" => Box::new(adapters::freewheelssp::Adapter::new(cfg.endpoint.clone())),
        "frvradn" => Box::new(adapters::frvradn::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "gamma" => Box::new(adapters::gamma::Adapter::new(cfg.endpoint.clone())),
        "gamoshi" => Box::new(adapters::gamoshi::Adapter::new(cfg.endpoint.clone())),
        "globalsun" => Box::new(adapters::globalsun::Adapter::new(cfg.endpoint.clone())),
        "gothamads" => Box::new(adapters::gothamads::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "grid" => Box::new(adapters::grid::Adapter::new(cfg.endpoint.clone())),
        "gumgum" => Box::new(adapters::gumgum::Adapter::new(cfg.endpoint.clone())),
        "huaweiads" => Box::new(adapters::huaweiads::Adapter::new(cfg.endpoint.clone(), &cfg.extra_adapter_info).map_err(|e| e.to_string())?),
        "imds" => Box::new(adapters::imds::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "impactify" => Box::new(adapters::impactify::Adapter::new(cfg.endpoint.clone())),
        "improvedigital" => Box::new(adapters::improvedigital::Adapter::new(cfg.endpoint.clone())),
        "infytv" => Box::new(adapters::infytv::Adapter::new(cfg.endpoint.clone())),
        "inmobi" => Box::new(adapters::inmobi::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "insticator" => Box::new(adapters::insticator::Adapter::new(cfg.endpoint.clone())),
        "interactiveoffers" => Box::new(adapters::interactiveoffers::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "intertech" => Box::new(adapters::intertech::Adapter::new(cfg.endpoint.clone())),
        "invibes" => Box::new(adapters::invibes::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "iqx" => Box::new(adapters::iqx::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "iqzone" => Box::new(adapters::iqzone::Adapter::new(cfg.endpoint.clone())),
        "ix" => Box::new(adapters::ix::Adapter::new(cfg.endpoint.clone())),
        "jixie" => Box::new(adapters::jixie::Adapter::new(cfg.endpoint.clone())),
        "kargo" => Box::new(adapters::kargo::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "kayzen" => Box::new(adapters::kayzen::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "kidoz" => Box::new(adapters::kidoz::Adapter::new(cfg.endpoint.clone())),
        "kiviads" => Box::new(adapters::kiviads::Adapter::new(cfg.endpoint.clone())),
        "kobler" => Box::new(adapters::kobler::Adapter::new(cfg.endpoint.clone())),
        "krushmedia" => Box::new(adapters::krushmedia::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "kueezrtb" => Box::new(adapters::kueezrtb::Adapter::new(cfg.endpoint.clone())),
        "lemmadigital" => Box::new(adapters::lemmadigital::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "limelightDigital" => Box::new(adapters::limelight_digital::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "lm_kiviads" => Box::new(adapters::lm_kiviads::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "lockerdome" => Box::new(adapters::lockerdome::Adapter::new(cfg.endpoint.clone())),
        "logan" => Box::new(adapters::logan::Adapter::new(cfg.endpoint.clone())),
        "logicad" => Box::new(adapters::logicad::Adapter::new(cfg.endpoint.clone())),
        "loopme" => Box::new(adapters::loopme::Adapter::new(cfg.endpoint.clone())),
        "loyal" => Box::new(adapters::loyal::Adapter::new(cfg.endpoint.clone())),
        "lunamedia" => Box::new(adapters::lunamedia::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "mabidder" => Box::new(adapters::mabidder::Adapter::new(cfg.endpoint.clone())),
        "madvertise" => Box::new(adapters::madvertise::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "marsmedia" => Box::new(adapters::marsmedia::Adapter::new(cfg.endpoint.clone())),
        "mediafuse" => Box::new(adapters::appnexus::Adapter::new(cfg).map_err(|e| e.to_string())?),
        "mediago" => Box::new(adapters::mediago::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "medianet" => Box::new(adapters::medianet::Adapter::new(cfg.endpoint.clone(), cfg.extra_adapter_info.clone())),
        "melozen" => Box::new(adapters::melozen::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "metax" => Box::new(adapters::metax::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "mgid" => Box::new(adapters::mgid::Adapter::new(cfg.endpoint.clone())),
        "mgidX" => Box::new(adapters::mgid_x::Adapter::new(cfg.endpoint.clone())),
        "minutemedia" => Box::new(adapters::minutemedia::Adapter::new(cfg.endpoint.clone())),
        "missena" => Box::new(adapters::missena::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "mobfoxpb" => Box::new(adapters::mobfoxpb::Adapter::new(cfg.endpoint.clone())),
        "mobilefuse" => Box::new(adapters::mobilefuse::Adapter::new(cfg.endpoint.clone())),
        "motorik" => Box::new(adapters::motorik::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "nativo" => Box::new(adapters::nativo::Adapter::new(cfg.endpoint.clone())),
        "nextmillennium" => Box::new(adapters::nextmillennium::Adapter::new(cfg.endpoint.clone(), &cfg.extra_adapter_info, server).map_err(|e| e.to_string())?),
        "nobid" => Box::new(adapters::nobid::Adapter::new(cfg.endpoint.clone())),
        "ogury" => Box::new(adapters::ogury::Adapter::new(cfg.endpoint.clone())),
        "oms" => Box::new(adapters::oms::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "onetag" => Box::new(adapters::onetag::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "openweb" => Box::new(adapters::openweb::Adapter::new(cfg.endpoint.clone())),
        "openx" => Box::new(adapters::openx::Adapter::new(cfg.endpoint.clone(), name.to_string())),
        "operaads" => Box::new(adapters::operaads::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "oraki" => Box::new(adapters::oraki::Adapter::new(cfg.endpoint.clone())),
        "orbidder" => Box::new(adapters::orbidder::Adapter::new(cfg.endpoint.clone())),
        "outbrain" => Box::new(adapters::outbrain::Adapter::new(cfg.endpoint.clone())),
        "ownadx" => Box::new(adapters::ownadx::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "pangle" => Box::new(adapters::pangle::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "pgamssp" => Box::new(adapters::pgamssp::Adapter::new(cfg.endpoint.clone())),
        "playdigo" => Box::new(adapters::playdigo::Adapter::new(cfg.endpoint.clone())),
        "pubmatic" => Box::new(adapters::pubmatic::Adapter::new(cfg.endpoint.clone())),
        "pubnative" => Box::new(adapters::pubnative::Adapter::new(cfg.endpoint.clone())),
        "pubrise" => Box::new(adapters::pubrise::Adapter::new(cfg.endpoint.clone())),
        "pulsepoint" => Box::new(adapters::pulsepoint::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "pwbid" => Box::new(adapters::pwbid::Adapter::new(cfg.endpoint.clone())),
        "qt" => Box::new(adapters::qt::Adapter::new(cfg.endpoint.clone())),
        "readpeak" => Box::new(adapters::readpeak::Adapter::new(cfg.endpoint.clone())),
        "relevantdigital" => Box::new(adapters::relevantdigital::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "resetdigital" => Box::new(adapters::resetdigital::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "revcontent" => Box::new(adapters::revcontent::Adapter::new(cfg.endpoint.clone())),
        "richaudience" => Box::new(adapters::richaudience::Adapter::new(cfg.endpoint.clone())),
        "rise" => Box::new(adapters::rise::Adapter::new(cfg.endpoint.clone())),
        "roulax" => Box::new(adapters::roulax::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "rtbhouse" => Box::new(adapters::rtbhouse::Adapter::new(cfg.endpoint.clone())),
        "rubicon" => Box::new(adapters::rubicon::Adapter::new(cfg, server)),
        "sa_lunamedia" => Box::new(adapters::sa_lunamedia::Adapter::new(cfg.endpoint.clone())),
        "screencore" => Box::new(adapters::screencore::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "seedingAlliance" => Box::new(adapters::seeding_alliance::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "seedtag" => Box::new(adapters::seedtag::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "sharethrough" => Box::new(adapters::sharethrough::Adapter::new(cfg.endpoint.clone())),
        "silvermob" => Box::new(adapters::silvermob::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "silverpush" => Box::new(adapters::silverpush::Adapter::new(cfg.endpoint.clone())),
        "smaato" => Box::new(adapters::smaato::Adapter::new(cfg.endpoint.clone())),
        "smartadserver" => Box::new(adapters::smartadserver::Adapter::new(cfg.endpoint.clone())),
        "smarthub" => Box::new(adapters::smarthub::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "smartrtb" => Box::new(adapters::smartrtb::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "smartx" => Box::new(adapters::smartx::Adapter::new(cfg.endpoint.clone())),
        "smartyads" => Box::new(adapters::smartyads::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "smilewanted" => Box::new(adapters::smilewanted::Adapter::new(cfg.endpoint.clone())),
        "smoot" => Box::new(adapters::smoot::Adapter::new(cfg.endpoint.clone())),
        "smrtconnect" => Box::new(adapters::smrtconnect::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "sonobi" => Box::new(adapters::sonobi::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "sovrn" => Box::new(adapters::sovrn::Adapter::new(cfg.endpoint.clone())),
        "sovrnXsp" => Box::new(adapters::sovrn_xsp::Adapter::new(cfg.endpoint.clone())),
        "sspBC" => Box::new(adapters::ssp_bc::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "stroeerCore" => Box::new(adapters::stroeer_core::Adapter::new(cfg.endpoint.clone())),
        "taboola" => Box::new(adapters::taboola::Adapter::new(&cfg.endpoint, server.gvl_id).map_err(|e| e.to_string())?),
        "tappx" => Box::new(adapters::tappx::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "teads" => Box::new(adapters::teads::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "telaria" => Box::new(adapters::telaria::Adapter::new(cfg.endpoint.clone())),
        "theadx" => Box::new(adapters::theadx::Adapter::new(cfg.endpoint.clone())),
        "thetradedesk" => Box::new(adapters::thetradedesk::Adapter::new(cfg.endpoint.clone(), cfg.extra_adapter_info.clone()).map_err(|e| e.to_string())?),
        "tpmn" => Box::new(adapters::tpmn::Adapter::new(cfg.endpoint.clone())),
        "tradplus" => Box::new(adapters::tradplus::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "trafficgate" => Box::new(adapters::trafficgate::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "triplelift" => Box::new(adapters::triplelift::Adapter::new(cfg.endpoint.clone())),
        "triplelift_native" => Box::new(adapters::triplelift_native::Adapter::new(cfg.endpoint.clone(), &cfg.extra_adapter_info).map_err(|e| e.to_string())?),
        "trustedstack" => Box::new(adapters::trustedstack::Adapter::new(cfg.endpoint.clone(), server.external_url.clone())),
        "ucfunnel" => Box::new(adapters::ucfunnel::Adapter::new(cfg.endpoint.clone())),
        "undertone" => Box::new(adapters::undertone::Adapter::new(cfg.endpoint.clone())),
        "unicorn" => Box::new(adapters::unicorn::Adapter::new(cfg.endpoint.clone())),
        "unruly" => Box::new(adapters::unruly::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "vidazoo" => Box::new(adapters::vidazoo::Adapter::new(cfg.endpoint.clone())),
        "videobyte" => Box::new(adapters::videobyte::Adapter::new(cfg.endpoint.clone())),
        "videoheroes" => Box::new(adapters::videoheroes::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "vidoomy" => Box::new(adapters::vidoomy::Adapter::new(cfg.endpoint.clone())),
        "visiblemeasures" => Box::new(adapters::visiblemeasures::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "visx" => Box::new(adapters::visx::Adapter::new(cfg.endpoint.clone())),
        "vox" => Box::new(adapters::vox::Adapter::new(cfg.endpoint.clone())),
        "vrtcal" => Box::new(adapters::vrtcal::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "vungle" => Box::new(adapters::vungle::Adapter::new(cfg.endpoint.clone())),
        "xeworks" => Box::new(adapters::xeworks::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "yahooAds" => Box::new(adapters::yahoo_ads::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "yandex" => Box::new(adapters::yandex::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "yeahmobi" => Box::new(adapters::yeahmobi::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "yieldlab" => Box::new(adapters::yieldlab::Adapter::new(cfg.endpoint.clone())),
        "yieldmo" => Box::new(adapters::yieldmo::Adapter::new(cfg.endpoint.clone())),
        "yieldone" => Box::new(adapters::yieldone::Adapter::new(cfg.endpoint.clone())),
        "zeroclickfraud" => Box::new(adapters::zeroclickfraud::Adapter::new(cfg.endpoint.clone()).map_err(|e| e.to_string())?),
        "zeta_global_ssp" => Box::new(adapters::zeta_global_ssp::Adapter::new(&cfg.endpoint).map_err(|e| e.to_string())?),
        "zmaticoo" => Box::new(adapters::zmaticoo::Adapter::new(cfg.endpoint.clone())),
        other => return Err(format!("unknown bidder: {other}")),
    })
}
