package matrix

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/prebid/prebid-server/v4/parity"
)

// RenderJSON writes the matrix rows to a JSON file.
func RenderJSON(rows []parity.MatrixRow, path string) error {
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal matrix: %w", err)
	}
	return os.WriteFile(path, data, 0o644)
}

// RenderMarkdown writes the matrix rows to a human-readable Markdown file.
func RenderMarkdown(rows []parity.MatrixRow, path string) error {
	var sb strings.Builder

	sb.WriteString("# Parity Compatibility Matrix\n\n")
	sb.WriteString("This file is auto-generated by `go run ./parity/cmd/update-matrix`.\n\n")
	sb.WriteString("| Domain | Status | Summary | Evidence |\n")
	sb.WriteString("|--------|--------|---------|----------|\n")

	for _, row := range rows {
		evidence := "—"
		if len(row.EvidenceLinks) > 0 {
			links := make([]string, len(row.EvidenceLinks))
			for i, l := range row.EvidenceLinks {
				links[i] = fmt.Sprintf("[%s](%s)", l.CaseID, l.ArtifactPath)
			}
			evidence = strings.Join(links, ", ")
		}

		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
			row.Domain, row.Status, row.Summary, evidence))
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*Generated from oracle evidence in `parity/out/auction/index.json`.*\n")

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
